server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aviation-events
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true

#  cache:
#    type: caffeine
#    caffeine:
#      spec: maximumSize=100, expireAfterAccess=5m

  application:
    name: "aviation-event-service"
    version: "1.0"

skytamer:
  url: "https://www.skytamer.com/"

#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: aviation-event-service-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.cache: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3
  instance:
    status-page-url-path: /actuator/health
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10



