server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flights
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  application:
    name: "Flight Service"
    version: "1.0"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: flight-data-processing
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      flight-requests: flight-requests
      airport-response: airport-response
      plane-response: plane-response

#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
