server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flights
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  application:
    name: "flight-service"
    version: "1.0"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: flight-data-processing
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      flight-requests: flight-requests
      report-requests: report-requests
      airport-response: airport-response
      plane-response: plane-response
      company-response: company-response
      aviation-event-response: aviation-event-response


  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 57a4d32caf422a
    password: 9ab22fe4a1f3e5
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3
  instance:
    status-page-url-path: /actuator/health
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
