server:
  port: 8084

spring:
  application:
    name: "report-service"
    version: "1.0"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: report-service-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3
  instance:
    status-page-url-path: /actuator/health
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

