server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plane
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100, expireAfterAccess=5m

  application:
    name: "Plane Service"
    version: "1.0"

logging:
  level:
    org.springframework.cache: TRACE



  #eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/



