INSERT INTO plane.plane (model, capacity, type, description)
VALUES ('Boeing 737-800', 189, 'PASSENGER', 'Popular model for short and medium-haul flights.'),
       ('Airbus A320', 240, 'PASSENGER', 'Commonly used for short flights, popular among airlines.'),
       ('Boeing 777-200', 317, 'PASSENGER', 'Long-haul aircraft known for comfort and efficiency.'),
       ('Airbus A350-900', 410, 'PASSENGER', 'Modern aircraft with advanced aerodynamics and comfort.'),
       ('Boeing 747-8', 660, 'PASSENGER', 'Known as "Jumbo Jet", used for long-distance travel.'),
       ('Embraer E195', 120, 'REGIONAL', 'Ideal for short and regional flights.'),
       ('Bombardier CRJ-900', 90, 'REGIONAL', 'Popular for short flights among regional airlines.'),
       ('Boeing 787-9', 296, 'PASSENGER', 'Long-haul aircraft with eco-friendly characteristics.'),
       ('Airbus A220-300', 160, 'PASSENGER', 'Modern aircraft designed for short and medium-haul flights.'),
       ('McDonnell Douglas MD-80', 172, 'PASSENGER', 'Widely used in American aviation.'),
       ('Boeing 757-200', 280, 'PASSENGER', 'Long-haul aircraft popular for flights between the US and Europe.'),
       ('Airbus A321', 240, 'PASSENGER', 'Larger version of the A320, used for longer flights.'),
       ('Boeing 767-300', 218, 'PASSENGER', 'Long-haul aircraft with a large capacity.'),
       ('Airbus A310', 280, 'PASSENGER', 'First aircraft with a wide body, popular in the 80s and 90s.'),
       ('ATR 72', 78, 'REGIONAL', 'Turboprop aircraft often used for regional flights.'),
       ('Boeing 737 MAX 8', 210, 'PASSENGER', 'Modern version of the 737 with improved fuel efficiency.'),
       ('Airbus A380', 850, 'PASSENGER',
        'The largest passenger aircraft in the world, ideal for high-capacity routes.'),
       ('Boeing 717', 110, 'REGIONAL', 'Compact passenger aircraft, ideal for short flights.'),
       ('Fokker 100', 122, 'REGIONAL', 'Popular for regional flights in Europe.'),
       ('Sukhoi Superjet 100', 108, 'REGIONAL', 'Modern regional aircraft with high comfort standards.'),
       ('Boeing 757-300', 243, 'PASSENGER', 'Longer version of the 757, popular for transatlantic flights.'),
       ('Airbus A319', 160, 'PASSENGER', 'Compact version of A320, often used for regional flights.'),
       ('Boeing 767-400', 245, 'PASSENGER', 'Longer model of the 767, used for long-haul flights.'),
       ('Airbus A321XLR', 244, 'PASSENGER', 'Long-range version of the A321, suitable for longer flights.'),
       ('Boeing 787-8', 242, 'PASSENGER', 'First model of the 787, known for efficiency and comfort.'),
       ('Boeing 737-700', 149, 'PASSENGER', 'Commonly used 737 model for short flights.'),
       ('Airbus A300', 266, 'PASSENGER', 'First wide-body aircraft, popular in the 70s and 80s.'),
       ('Boeing 767-300ER', 218, 'PASSENGER', 'Extended range version of the 767-300.'),
       ('Airbus A310-300', 280, 'PASSENGER', 'Used for regional and international flights.'),
       ('Boeing 737-900ER', 200, 'PASSENGER', 'Extended range version of the 737-900.'),
       ('Airbus A330-200', 240, 'PASSENGER', 'Long-haul aircraft with a large capacity.'),
       ('Airbus A340-300', 250, 'PASSENGER', 'Four-engine long-haul aircraft.'),
       ('Boeing 787-10', 318, 'PASSENGER', 'Longest version of the 787 series.'),
       ('Boeing 777-300ER', 368, 'PASSENGER', 'Extended range version of the 777-300.'),
       ('Airbus A350-1000', 410, 'PASSENGER', 'Largest version of the A350 series.'),
       ('Boeing 737 MAX 9', 220, 'PASSENGER', 'Newer variant of the MAX series with higher capacity.'),
       ('Boeing 747-400', 416, 'PASSENGER', 'Older version of the Jumbo Jet, widely used in the 90s and 2000s.'),
       ('Airbus A380-800', 555, 'PASSENGER', 'Largest passenger aircraft, ideal for high-density routes.'),
       ('Boeing 757-500', 240, 'PASSENGER', 'Proposed version of the 757, not produced.'),
       ('McDonnell Douglas MD-11', 285, 'PASSENGER', 'Wide-body tri-jet aircraft, popular in the 90s.'),
       ('Fokker 70', 70, 'REGIONAL', 'Regional jet, used for short flights.'),
       ('Bombardier CRJ-1000', 100, 'REGIONAL', 'Latest addition to the CRJ family, popular among regional airlines.'),
       ('Embraer ERJ 145', 50, 'REGIONAL', 'Regional jet, widely used in the US and Europe.'),
       ('Airbus A321neo', 240, 'PASSENGER', 'New engine option for the A321, with improved fuel efficiency.'),
       ('Boeing 767-400ER', 245, 'PASSENGER', 'Extended range version of the 767-400.'),
       ('Boeing 737-600', 110, 'PASSENGER', 'Smaller variant of the 737, used for regional routes.'),
       ('Airbus A310-200', 280, 'PASSENGER', 'Older version of the A310, used primarily in the 80s and 90s.'),
       ('Boeing 757-200PF', 200, 'PASSENGER', 'Freighter version of the 757-200.'),
       ('Airbus A220-100', 100, 'PASSENGER', 'Smaller version of the A220 series.'),
       ('Boeing 737-900ER', 220, 'PASSENGER', 'Extended range version of the 737-900.'),
       ('Airbus A321LR', 240, 'PASSENGER', 'Long-range version of the A321.'),
       ('Boeing 747-400F', 400, 'PASSENGER', 'Freighter version of the 747-400.'),
       ('Airbus A350-900ULR', 440, 'PASSENGER', 'Ultra-long range version of the A350-900.'),
       ('Boeing 767-300F', 218, 'PASSENGER', 'Freighter version of the 767-300.'),
       ('McDonnell Douglas MD-82', 170, 'PASSENGER', 'Popular among airlines in the 80s and 90s.'),
       ('Airbus A318', 132, 'PASSENGER', 'Smallest member of the A320 family.'),
       ('Boeing 787-9 Dreamliner', 296, 'PASSENGER', 'Enhanced version of the 787 with better efficiency.'),
       ('Boeing 777X', 384, 'PASSENGER', 'Newest addition to the 777 family, featuring advanced technology.');
