ALTER TABLE plane.plane
    ADD COLUMN average_speed INT;

UPDATE plane.plane SET average_speed = 828 WHERE model = 'Boeing 737-800';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A320';
UPDATE plane.plane SET average_speed = 905 WHERE model = 'Boeing 777-200';
UPDATE plane.plane SET average_speed = 903 WHERE model = 'Airbus A350-900';
UPDATE plane.plane SET average_speed = 910 WHERE model = 'Boeing 747-8';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Embraer E195';
UPDATE plane.plane SET average_speed = 833 WHERE model = 'Bombardier CRJ-900';
UPDATE plane.plane SET average_speed = 913 WHERE model = 'Boeing 787-9';
UPDATE plane.plane SET average_speed = 835 WHERE model = 'Airbus A220-300';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'McDonnell Douglas MD-80';
UPDATE plane.plane SET average_speed = 855 WHERE model = 'Boeing 757-200';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A321';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Boeing 767-300';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Airbus A310';
UPDATE plane.plane SET average_speed = 500 WHERE model = 'ATR 72';
UPDATE plane.plane SET average_speed = 839 WHERE model = 'Boeing 737 MAX 8';
UPDATE plane.plane SET average_speed = 900 WHERE model = 'Airbus A380';
UPDATE plane.plane SET average_speed = 780 WHERE model = 'Boeing 717';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Fokker 100';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Sukhoi Superjet 100';
UPDATE plane.plane SET average_speed = 855 WHERE model = 'Boeing 757-300';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A319';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Boeing 767-400';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A321XLR';
UPDATE plane.plane SET average_speed = 913 WHERE model = 'Boeing 787-8';
UPDATE plane.plane SET average_speed = 828 WHERE model = 'Boeing 737-700';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Airbus A300';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Boeing 767-300ER';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Airbus A310-300';
UPDATE plane.plane SET average_speed = 839 WHERE model = 'Boeing 737-900ER';
UPDATE plane.plane SET average_speed = 890 WHERE model = 'Airbus A330-200';
UPDATE plane.plane SET average_speed = 900 WHERE model = 'Airbus A340-300';
UPDATE plane.plane SET average_speed = 913 WHERE model = 'Boeing 787-10';
UPDATE plane.plane SET average_speed = 905 WHERE model = 'Boeing 777-300ER';
UPDATE plane.plane SET average_speed = 903 WHERE model = 'Airbus A350-1000';
UPDATE plane.plane SET average_speed = 839 WHERE model = 'Boeing 737 MAX 9';
UPDATE plane.plane SET average_speed = 910 WHERE model = 'Boeing 747-400';
UPDATE plane.plane SET average_speed = 900 WHERE model = 'Airbus A380-800';
UPDATE plane.plane SET average_speed = 240 WHERE model = 'Boeing 757-500';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'McDonnell Douglas MD-11';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Fokker 70';
UPDATE plane.plane SET average_speed = 833 WHERE model = 'Bombardier CRJ-1000';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Embraer ERJ 145';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A321neo';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Boeing 767-400ER';
UPDATE plane.plane SET average_speed = 828 WHERE model = 'Boeing 737-600';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'Airbus A310-200';
UPDATE plane.plane SET average_speed = 200 WHERE model = 'Boeing 757-200PF';
UPDATE plane.plane SET average_speed = 835 WHERE model = 'Airbus A220-100';
UPDATE plane.plane SET average_speed = 839 WHERE model = 'Boeing 737-900ER';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A321LR';
UPDATE plane.plane SET average_speed = 400 WHERE model = 'Boeing 747-400F';
UPDATE plane.plane SET average_speed = 440 WHERE model = 'Airbus A350-900ULR';
UPDATE plane.plane SET average_speed = 850 WHERE model = 'Boeing 767-300F';
UPDATE plane.plane SET average_speed = 800 WHERE model = 'McDonnell Douglas MD-82';
UPDATE plane.plane SET average_speed = 840 WHERE model = 'Airbus A318';
UPDATE plane.plane SET average_speed = 913 WHERE model = 'Boeing 787-9 Dreamliner';
UPDATE plane.plane SET average_speed = 905 WHERE model = 'Boeing 777X';
