server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airport
  application:
    name: "Airport Service"
    version: "1.0"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
